language: ruby
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.9
env:
  - RAILS=3.2.22.1
  - RAILS=4.1.14.1
  - RAILS=4.2.5.1
  - RAILS=5.0.0.0
matrix:
  exclude:
    - rvm: 2.1.9
      env: RAILS=5.0.0.0
before_install:
  - gem update bundler
sudo: false
cache: bundler
